### ISSUE TITLE
GP-IB support?

### ISSUE THREAD

**Issue by walshbig** [NoyemiK/KOLIN2-Demos-for-PC-9801#1]
Hello

Is it possible to include the GP-IB support? I need this support for controlling our instrument. Board inside PC-9801 computer is "PC-9801-29n" or "PC-9801-29" or "PC-9801-29k" but modern computer has GPIB NI GPIB-PCII/IIA inside.

thx

**Comment by NoyemiK** [comment]
You'll have to ask the original author of the driver, "Akikaz". I have no idea how to contact him since the driver documentation for Kolin2 only includes a telephone/fax I can't call (and is probably out of date) but you may be able to ask Takeshi Abo (@valsound on twitter) how to get contact with him.

**Comment by walshbig** [comment]
Cpuld you please email me a copy of the driver documentation for Kolin2 to jackwalshbig (at) gmail (dot) com?

thx
